# ansible/roles/server-setup/tasks/main.yml
---
- name: Install passlib
  ansible.builtin.apt:
    name: python3-passlib
    state: present
  become: yes

- name: Ensure the hash user exists
  ansible.builtin.user:
    name: hash
    password: "{{ hash_password | password_hash('sha512') }}"
    shell: /bin/bash
    create_home: yes
    state: present

- name: Add hash user to sudoers
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/hash
    line: 'hash ALL=(ALL) NOPASSWD:ALL'
    create: yes
    validate: 'visudo -cf %s'
