# ansible/roles/server-setup/tasks/main.yml
---
- name: Create user 'hash'
  user:
    name: "{{ user_name }}"
    password: "{{ hash_password | password_hash('sha512') }}"
    groups: sudo,docker
    shell: /bin/bash

- name: Configure passwordless sudo
  copy:
    dest: /etc/sudoers.d/{{ user_name }}
    content: "{{ user_name }} ALL=(ALL) NOPASSWD: ALL"
    validate: 'visudo -cf %s'

- name: Install Docker stack
  apt:
    name:
      - docker.io
      - docker-compose
    update_cache: yes

- name: Configure SSH
  block:
    - name: Enable password auth
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication yes'
        
    - name: Keep root login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin yes'
  notify: restart sshd