# ansible/roles/server-setup/tasks/main.yml
---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  become: yes

- name: Upgrade system packages
  ansible.builtin.apt:
    upgrade: dist
    cache_valid_time: 3600
  become: yes

- name: Install Python and dependencies
  ansible.builtin.apt:
    name:
      - python3
      - python3-pip
      - python3-passlib
    state: present
  become: yes

- name: Install passlib via pip (system-wide)
  ansible.builtin.pip:
    name: passlib
    executable: pip3
  become: yes

- name: Validate Python environment
  command: python3 -c "import passlib; print(passlib.__version__)"
  register: passlib_check
  changed_when: false
  ignore_errors: yes

- name: Debug passlib status
  debug:
    msg: "Passlib version: {{ passlib_check.stdout | default('NOT FOUND') }}"

- name: Ensure the hash user exists
  ansible.builtin.user:
    name: hash
    password: "{{ hash_password | password_hash('sha512') }}"
    shell: /bin/bash
    create_home: yes
    state: present

- name: Add hash user to sudoers
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/hash
    line: 'hash ALL=(ALL) NOPASSWD:ALL'
    create: yes
    validate: 'visudo -cf %s'
