# ansible/playbook.yml
---
- hosts: all
  pre_tasks:
    - name: Ensure passlib is installed (local)
      delegate_to: localhost
      become: true
      pip:
        name: passlib
        state: present
  roles:
    - server-setup