# .github/workflows/deploy.yml
name: Auto-Server-Setup

on:
  push:
    branches: [main]

jobs:
  provision:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass python3-venv

      - name: Create and activate virtual environment
        run: |
          python3 -m venv ansible-venv
          source ansible-venv/bin/activate
          pip install --upgrade pip

      - name: Install Python requirements
        run: |
          source ansible-venv/bin/activate
          pip install ansible passlib

      - name: Prepare inventory
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          ROOT_PASS: ${{ secrets.ROOT_PASSWORD }}
        run: |
          sed -i "s/%SERVER_IP%/$SERVER_IP/g" ansible/inventory.ini
          sed -i "s/%ROOT_PASSWORD%/$ROOT_PASS/g" ansible/inventory.ini

      - name: Run Ansible Playbook
        env:
          HASH_PASS: ${{ secrets.HASH_PASSWORD }}
        run: |
          source ansible-venv/bin/activate
          ansible-playbook \
            -i ansible/inventory.ini \
            -e "hash_password=$HASH_PASS" \
            ansible/playbook.yml

      - name: Validate Setup
        run: |
          sshpass -p "$HASH_PASS" ssh -o StrictHostKeyChecking=no hash@${{ secrets.SERVER_IP }} \
            "sudo docker run --rm hello-world"